version: "3.3"
networks:
  dev:
    name: dev
services:
  nginx:
    image: sonntuet1997/ai-assignment-proxy:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:80
    environment:
      - API_URL
      - UI_URL
    restart: "always"
    networks:
      - dev
  nextjs:
    image: sonntuet1997/ai-assignment-ui:dev
    build:
      context: ../../
      dockerfile: Dockerfile
    networks:
      - dev